### ISSUE TITLE
Support for log levels?

### ISSUE THREAD

**Issue by Bradleykingz** [r37r0m0d3l/consono#119]
Like the title suggests - do you plan on supporting log levels any time soon?

**Comment by r37r0m0d3l** [comment]
Okay. I'm not exactly understand what you really want. `console.error()` and `console.warn()` goes to `stderr`. Everything else goes to `stdout`.
You can run this code if you wish for `stderr` output:
```js
console.error(consonoReturn("Some value"));
console.warning(consonoReturn("Some value"));
```
Or you want internal call of `console`? In example `consono.error()`, `consono.dir()`?

**Comment by Bradleykingz** [comment]
I didn't realize I could do that. Thanks!  :+1:
